apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zomato
  name: movies-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
    spec:
      containers:
      - name: cont1
        image: sivanankatta/movies:latest

        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
    - port: 80
      targetPort: 80
